server:
  port: 8080

spring:
  datasource:
    username: root
    password: z9426464
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.nanjolono.test.mapper

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
